# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebasePracticeProject' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebasePracticeProject
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'FirebasePracticeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebasePracticeProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
